### ISSUE TITLE
Multi-Mission Gear incorrect stat

### ISSUE THREAD

**Issue by hen** [zz1000zz/OCTGN_TF#17]
MMG should be 1-Def; it currently says 2-Def.

**Comment by zz1000zz** [comment]
Thanks.  Should be fixed in the next update, though I'm not sure how relevant that is with the card being banned now.  Speaking of, I've wondered if I should do anything to show a card is banned/limited.  There are some complexities to doing so should we ever get rotation/different formats, it might

**Comment by hen** [comment]
It's still legal for Limited, so good to keep it, especially as we support the random boosters more.
