### ISSUE TITLE
Handle KO'd Battlemaster's specially

### ISSUE THREAD

**Issue by hen** [zz1000zz/OCTGN_TF#55]
When KO'ing a Battlemaster, or Cog, heal them and switch modes.

KO code (adding around the start of the KO function):

    # Instead of KO'ing, flip the character to upgrade mode and heal it
    def flipCharacterToUpgrade(card):
        awaken(card)
        card.markers[CounterMarker] = 0
    
    def KO(card, x=0, y=0):
        mute()
    
        if( ("Battle Master" in card.trait and card.alternate == card.alternates[1]) or "Sergeant Cog - Artillery, Mechanic" in card.name):
            flipCharacterToUpgrade(card)
            return

**Comment by hen** [comment]
Possibly also nice to KO Brunt/Six-Gun and play their upgrades.

**Comment by zz1000zz** [comment]
Hard coding individual card names into functions is undesirable so this should be revisited to try to properly generalize.  It may be possible to special case Brunt/Six-Gun in the process.  That said, change has been accepted with minor alterations:

1) The condition to address the account for the recent change to these cards' alternates and an alteration to include the alternate check on Cog.  Checking Cog's alternate status is unlikely to ever be relevant, but there's no harm.
2) Didn't break any code out into a separate function.  Seemed little purpose given the limited code unless/until special cases for Brunt/Six-Gun are added, at which point the function structure would need to be changed anyway.
3) Rotated the card to vertical orientation since there's no reason for the upgrade to be "tapped."
