### ISSUE TITLE
[Wave 4] Battle Masters are backwards

### ISSUE THREAD

**Issue by hen** [zz1000zz/OCTGN_TF#60]
The Wave 4 Battle Masters didn't get switched in the set.xml so that Bot Mode is their first mode.

**Comment by zz1000zz** [comment]
This problem is recognized.  When Battle Masters in Wave 3 were flipped to be correct, Wave 4 Battle Masters got overlooked.  The current issue is trying to figure out an effective way to swap the sides without breaking images for players.  Currently examining options that won't require users download a new image pack.

**Comment by hen** [comment]
A side effect of this is that the W4 Battle Masters are added to the Character deck as their upgrade modes.

**Comment by zz1000zz** [comment]
I forgot to close this ticket several months ago when this issue was resolved.  Closing it now.
